
-- posts table
CREATE TABLE posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL CHECK (char_length(content) <= 512),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  like_count INT DEFAULT 0 NOT NULL
);

-- comments table
CREATE TABLE comments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE NOT NULL,
  content TEXT NOT NULL CHECK (char_length(content) <= 512),
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL
);

-- likes table
CREATE TABLE likes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  UNIQUE(post_id)
);

-- function to increment like count
CREATE OR REPLACE FUNCTION increment_like_count(post_id_param BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE posts
  SET like_count = like_count + 1
  WHERE id = post_id_param;
END;
$$ LANGUAGE plpgsql;

-- function to decrement like count
CREATE OR REPLACE FUNCTION decrement_like_count(post_id_param BIGINT)
RETURNS void AS $$
BEGIN
  UPDATE posts
  SET like_count = like_count - 1
  WHERE id = post_id_param;
END;
$$ LANGUAGE plpgsql;
